#ifndef SMARTPROXY_LWIPOPTS_H
#define SMARTPROXY_LWIPOPTS_H

#define NO_SYS 1
#define SYS_LIGHTWEIGHT_PROT 0
#define LWIP_SOCKET 0
#define LWIP_NETCONN 0
#define LWIP_DNS 0

#define LWIP_IPV4 1
#define LWIP_IPV6 1
#define LWIP_TCP 1
#define LWIP_UDP 1
#define LWIP_ICMP 1
#define LWIP_ICMP6 1

#define LWIP_ARP 0
#define LWIP_ETHERNET 0
#define LWIP_DHCP 0
#define LWIP_DHCP6 0
#define LWIP_AUTOIP 0
#define LWIP_IGMP 0
#define LWIP_MLD 0
#define LWIP_SNMP 0
#define LWIP_HTTPD 0

#define LWIP_STATS 0
#define LWIP_DEBUG 0
#define LWIP_PROVIDE_ERRNO 0

#define CHECKSUM_CHECK_IP 0
#define CHECKSUM_CHECK_UDP 0
#define CHECKSUM_CHECK_TCP 0
#define CHECKSUM_CHECK_ICMP 0
#define CHECKSUM_CHECK_ICMP6 0
#define LWIP_CHECKSUM_ON_COPY 1
#define SO_REUSE 1
#define IP_REASSEMBLY 1
#define IP_FRAG 1

#define MEM_ALIGNMENT 4
#define MEM_SIZE (8 * 1024 * 1024)
#define PBUF_POOL_SIZE 2048
#define MEMP_NUM_TCP_PCB 512
#define MEMP_NUM_TCP_PCB_LISTEN 32
#define MEMP_NUM_TCP_SEG 4096
#define MEMP_NUM_UDP_PCB 512
#define MEMP_NUM_PBUF 2048

#define TCP_MSS 1460
#define LWIP_WND_SCALE 1
#define TCP_RCV_SCALE 4
#define TCP_SND_BUF (384 * TCP_MSS)
#define TCP_WND (384 * TCP_MSS)
#define TCP_SNDLOWAT (16 * TCP_MSS)
#define TCP_QUEUE_OOSEQ 1
#define LWIP_TCP_SACK_OUT 1
#define LWIP_TCP_KEEPALIVE 1
#define LWIP_TCP_TIMESTAMPS 1
#define LWIP_NETIF_TX_SINGLE_PBUF 1

#endif
