#!/usr/bin/env bash
# 每月自动更新 chnroute.txt(GitHub Actions update-chnroute 工作流调用;本地可 dry-run)。
#
# 拉取 mayaxcn/china-ip-list 的中国 IP 段(v4 + v6),过滤内网/保留段,合并生成
# 带「更新时间」注释头的 chnroute 文件,写入桌面端根目录 + Android assets 两处副本。
# 数据未变化时不写文件(时间戳保留),避免每月无谓 commit。
#
# 用法:
#   bash scripts/update-chnroute.sh [OUT_V4] [OUT_V6]
#   默认 OUT_V4=chnroute.txt, OUT_V6=android/app/src/main/assets/chnroute.txt;
#   本地验证可传临时路径,不碰仓库文件。
set -euo pipefail
export LC_ALL=C   # sort -u 字节稳定,防跨运行因 locale 抖动产生假 diff

V4_URL="https://raw.githubusercontent.com/mayaxcn/china-ip-list/master/chnroute.txt"
V6_URL="https://raw.githubusercontent.com/mayaxcn/china-ip-list/master/chnroute_v6.txt"

# 防空/半空提交:过滤后条数低于阈值即 abort(实测 v4≈8789 / v6≈2041,远高于阈值)。
MIN_V4="${MIN_V4:-1000}"
MIN_V6="${MIN_V6:-100}"
OUT_V4="${1:-chnroute.txt}"
OUT_V6="${2:-android/app/src/main/assets/chnroute.txt}"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

# 源文件非 2xx(含网络失败)即 set -e 中止,不会拿空数据往下走。
curl --fail --location --silent --show-error \
  --connect-timeout 15 --max-time 120 --retry 3 --retry-delay 2 \
  "$V4_URL" -o "$tmp/v4.raw"
curl --fail --location --silent --show-error \
  --connect-timeout 15 --max-time 120 --retry 3 --retry-delay 2 \
  "$V6_URL" -o "$tmp/v6.raw"

# v4:提取 CIDR,排除内网/保留段(沿用既有过滤语义)。
grep -Eo '([0-9]+\.){3}[0-9]+(/[0-9]{1,2})?' "$tmp/v4.raw" \
  | grep -Ev '^192\.168|^172\.1[6-9]\.|^172\.2[0-9]\.|^172\.3[0-2]\.|^10\.|^127\.|^255\.|^0\.' \
  | sort -u > "$tmp/v4.txt"

# v6:提取 CIDR,排除回环 ::1/128。
grep -Eo '(([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|(([0-9a-fA-F]{1,4}:){6})([0-9.]+))/[0-9]+' "$tmp/v6.raw" \
  | grep -Ev '^::1/128' \
  | sort -u > "$tmp/v6.txt"

n4="$(wc -l < "$tmp/v4.txt")"
n6="$(wc -l < "$tmp/v6.txt")"
if [ "$n4" -lt "$MIN_V4" ] || [ "$n6" -lt "$MIN_V6" ]; then
  echo "abort: counts below threshold (v4=$n4 < $MIN_V4 or v6=$n6 < $MIN_V6)" >&2
  exit 1
fi

cat "$tmp/v4.txt" "$tmp/v6.txt" > "$tmp/payload"

# 读取旧文件头部「上次更新时间」(无注释头则为空)。
prev_ts=""
if [ -f "$OUT_V4" ]; then
  prev_ts="$(grep -m1 '^# Updated:' "$OUT_V4" | sed -E 's/^# Updated: *//' || true)"
fi

# 数据对比:去旧文件注释头后的 payload 与本次生成逐行比对,相同则不更新。
if [ -f "$OUT_V4" ]; then
  grep -v '^#' "$OUT_V4" | sed '/^[[:space:]]*$/d' > "$tmp/old_payload"
  if cmp -s "$tmp/old_payload" "$tmp/payload"; then
    echo "chnroute data unchanged (prev update: ${prev_ts:-none}); skipping (v4=$n4 v6=$n6)"
    exit 0
  fi
fi

TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
{
  printf '# Auto-generated by SmartProxy CI - scripts/update-chnroute.sh\n'
  printf '# Updated: %s (UTC)\n' "$TS"
  printf '# DO NOT EDIT MANUALLY - overwritten by monthly CI update\n'
  printf '# Source v4: %s\n' "$V4_URL"
  printf '# Source v6: %s\n' "$V6_URL"
  printf '# IPv4 entries: %s\n' "$n4"
  printf '# IPv6 entries: %s\n' "$n6"
  cat "$tmp/payload"
} > "$OUT_V4"
cp "$OUT_V4" "$OUT_V6"

echo "chnroute updated (prev update: ${prev_ts:-none}) -> $OUT_V4 and $OUT_V6 (v4=$n4 v6=$n6)"
